version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${PRODUCT_MONGO_USERMANE}
      - MONGO_INITDB_ROOT_PASSWORD=${PRODUCT_MONGO_PASSWORD}
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  data: {}

networks:
  default:
    name: mongodb_network